# embedded profile configuration (change url from GTTEST to GTDB for use main database)

spring:
  main:
    banner-mode: console

server:
  compression:
    enabled: true
  port: 8080

app:
  sapod:
    datasource:
      jndi-name: "jdbc/GTMAIN"
#        url: jdbc:db2://10.4.253.43:50000/TEST:currentSchema=GTMAIN;
#        username: dbgtuser
#        password: 123qwe
      url: jdbc:db2://10.4.253.161:50000/GTTEST:currentSchema=GTMAIN;
      username: u352gtdb
      password: 165#z15fa3&
      driverClassName: com.ibm.db2.jcc.DB2Driver
  pensi:
    datasource:
      jndi-name: "jdbc/GTPENSI"
#      url: jdbc:db2://10.4.253.43:50000/TEST:currentSchema=GTPENSI;
#      username: dbgtuser
#      password: 123qwe
      url: jdbc:db2://10.4.253.161:50000/GTTEST:currentSchema=GTPENSI;
      username: u352gtdb
      password: 165#z15fa3&
      driverClassName: com.ibm.db2.jcc.DB2Driver
  mq:
    #enable: true
    queue-manager:
      jndi-name: "jms/GT.QCF"
      queueManager: TEST_QUEUE_MANAGER
      channel: MQ.CLIENT.CHANNEL
      connName: 10.4.253.43(1414)
      user: mqclient
      password: 123qwe
    inbound:
      jndi-name: "jms/GT.IN.Q"
      name: "Q.IN"
    outbound:
      jndi-name: "jms/GT.OUT.Q"
      name: "Q.OUT"

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: trace
