# production configuration
app:
  settings:
    jndi-name: "config/GTSETTINGS"
  sapod:
    datasource:
      jndi-name: "jdbc/GTMAIN"
  pensi:
    datasource:
      jndi-name: "jdbc/GTPENSI"
  mq:
    enable: true
    caching: true
    queue-manager:
      jndi-name: "jms/GT.QCF"
    inbound:
      jndi-name: "jms/GT.IN.Q"
    outbound:
      jndi-name: "jms/GT.OUT.Q"
  mailer:
    enable: true
    jndi-name: "mail/GT.MAIL"

