# test profile configuration

server:
  compression:
    enabled: true
  port: 8080

app:
  sapod:
    datasource:
      url: jdbc:db2://10.4.253.43:50000/TESTDB1
      username: sapod
      password: 123qwedsacxz
      driverClassName: com.ibm.db2.jcc.DB2Driver
  pensi:
    datasource:
      url: jdbc:db2://10.4.253.43:50000/TESTDB1
      username: pensi
      password: 123qwedsacxz
      driverClassName: com.ibm.db2.jcc.DB2Driver
  mq:
    enable: false
    queue-manager:
      queueManager: TEST_QUEUE_MANAGER
      channel: MQ.CLIENT.CHANNEL
      connName: 10.4.253.43(1414)
      user: mqclient
      password: 123qwe
    inbound:
      name: "Q.IN"
    outbound:
      name: "Q.OUT"
