# embedded profile configuration (change url from GTTEST to GTDB for use main database)

spring:
  main:
    banner-mode: console

server:
  compression:
    enabled: true
  port: 8080

app:
#  settings:
#    newServiceCodes: true
#  api:
#    security: "none"
  sapod:
    datasource:
      jndi-name: "jdbc/GTMAIN"
      url: jdbc:db2://10.4.253.161:50000/GTTEST:currentSchema=GTMAIN;
      username: u352gtdb
      password: 165#z15fa3&
      driverClassName: com.ibm.db2.jcc.DB2Driver
    jpa:
      show-sql: true
  pensi:
    datasource:
      jndi-name: "jdbc/GTPENSI"
      url: jdbc:db2://10.4.253.161:50000/GTTEST:currentSchema=GTPENSI;
      username: u352gtdb
      password: 165#z15fa3&
      driverClassName: com.ibm.db2.jcc.DB2Driver
    jpa:
      show-sql: true
  mq:
    #enable: true
    caching: true
    queue-manager:
      jndi-name: "jms/GT.QCF"
      queueManager: QM1
      channel: TEST.CHANNEL
      connName: 10.4.253.58(1414)
      user: mqmuser01
      password: Py33705
    inbound:
      jndi-name: "jms/GT.IN.Q"
      name: "IN.TEST"
    outbound:
      jndi-name: "jms/GT.OUT.Q"
      name: "OUT.TEST"
  mailer:
    enable: false
    jndi-name: "mail/GT.MAIL"
    host: "mail.ktc.rw"
    port: 25
    username: "sapod@ktc.rw"
    password: ""
    properties:
      gt.mailer.from: "AS GT <gt@ktc.rw>"
      gt.mailer.to: "sapod@ktc.rw"
      gt.mailer.subject: "AS GT [${gt.server.ip}]"
      gt.mailer.event.rates: false
      gt.mailer.event.errors: true
      gt.mailer.event.startup: true
